name: Main

on: [push]

jobs:

  test-1-3-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
          pip install "cachier==1.3.0"

      - shell: python
        run: |
          import os
          from cachier import cachier

          def test():
            sf = './side_effect'
            if os.path.isfile(sf):
              os.remove(sf)

            @cachier(cache_dir='./cache')
            def foo(x):
              with open(sf, 'w') as f:
                f.write('data')
              return True

            foo('test')

            return os.path.isfile(sf)

          assert test()
          assert not test()
