name: Main

on: [push]

jobs:

  test-1-3-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: ls -a

      - run: |
          python -m pip install --upgrade pip
          pip install "cachier==1.3.0"

      # test() returns True if NO cache was used
      # 

      - shell: python
        run: |
          from cachier_test import cachier_test

          assert cachier_test.test()
          assert not cachier_test.test()

      - run: |
          ls -a ./cache

      - shell: python
        run: |
          from cachier_test import test

          assert not cachier_test.test()
          assert not cachier_test.test()
