name: Main

on:
  push:
    branches:
      - "*"

jobs:

  test-1-3-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
          pip install "cachier==1.3.0"

      - shell: python
        run: |
          from cachier import cachier

          def test():
            value = False

            @cachier(cache_dir='./cache')
            def foo(x):
              value = True
              return True

            foo('test')

            return value

          assert test()
          assert not test()

      - shell: python
        run: |
          from cachier import cachier

          def test():
            value = False

            @cachier(cache_dir='./cache')
            def foo(x):
              value = True
              return True

            foo('test')

            return value

          assert not test()
          assert not test()