name: Main

on: [push]

jobs:

  test-1-3-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: ls -a

      - run: |
          python -m pip install --upgrade pip
          pip install "cachier==1.3.0"

      - shell: python
        run: |
          import sys,os
          sys.path.append(os.getcwd())
          from cachier_test import cache_was_used

          assert cache_was_used() == False
          assert cache_was_used() == True
          assert cache_was_used() == True
          assert cache_was_used() == True

      - name: Proof that cache was stored on disk
        run: |
          ls -a ./cache
          cat ./cache/.cachier_test.foo

      - shell: python
        run: |
          import sys,os
          sys.path.append(os.getcwd())
          from cachier_test import cache_was_used

          assert cache_was_used() == True, "We didn't use .cachier_test.foo"
          assert cache_was_used() == True

          
  test-1-2-8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: ls -a

      - run: |
          python -m pip install --upgrade pip
          pip install "cachier==1.2.8"

      - shell: python
        run: |
          import sys,os
          sys.path.append(os.getcwd())
          from cachier_test import cache_was_used

          assert cache_was_used() == False
          assert cache_was_used() == True
          assert cache_was_used() == True
          assert cache_was_used() == True

      - name: Proof that cache was stored on disk
        run: |
          ls -a ./cache
          cat ./cache/.cachier_test.foo

      - shell: python
        run: |
          import sys,os
          sys.path.append(os.getcwd())
          from cachier_test import cache_was_used

          assert cache_was_used() == True, "We didn't use .cachier_test.foo"
          assert cache_was_used() == True
