name: Main

on: [push]

jobs:

  test-1-3-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
          pip install "cachier==1.3.0"

      - shell: python
        run: |
          from cachier_test import test

          assert test()
          assert not test()

      - run: |
          ls -a ./cache

      - shell: python
        run: |
          from cachier_test import test

          assert not test()
          assert not test()
